# Database configuration
POSTGRES_HOST=judge0-db
POSTGRES_PORT=5432
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=judge0

# Redis configuration
REDIS_HOST=redis
REDIS_PORT=6379

# Basic Settings
# Authentication is optional for local development
# Use an empty string if you don't want to use a token
AUTH_TOKEN=
